import Head from 'next/head';

import { Poppins } from 'next/font/google'
import './globals.css'
import "bootstrap-icons/font/bootstrap-icons.css";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap" />
      </Head>
      <body>
        {children}
      </body>
    </html>
  )
}
